version: '3'

services:
  mysql:
    platform: linux/amd64
    image: mysql:8.0.23
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      interval: 1s
      timeout: 3s
      retries: 30

  redis:
    image: redis:6.0.5
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis
