version: '3'

services:
  mysql:
    image: arm64v8/mysql:8-oracle
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      interval: 1s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7.0.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis
